### ISSUE TITLE
[FEAT] 데이터베이스 구현

### ISSUE THREAD

**Issue by hwiwonK** [hwiwonK/MacC-Team-Maddori.Apple-Server#7]
## 💡 Issue

데이터베이스 구현
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/67336936/197388076-c81f2d77-64df-4ff5-b838-38392e117b8a.png">

## 📝  Todo
- [x] 데이터베이스 생성
- [x] 데이터베이스 연결
- [x] user 테이블
- [x] user_team 테이블
- [x] team 테이블
- [x] reflection 테이블
- [x] css 테이블
- [x] association 설정

**Comment by dangsal** [comment]
메리 화이팅!
